name: Check Pull Request

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v5

      - name: Run luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: -q .
