name: Check Pull Request

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v5

      - name: Run luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: -q .

      - name: Install lua
        uses: luarocks/gh-actions-lua@v11

      - name: luatest
        run: lua -v
