name: Check Pull Request
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v6
      - name: Run luacheck
        uses: dekallo/luacheck@main
        with:
          args: -q
          custom_script: scripts/ci_validate.lua
          custom_args: .
          job_summary: true
