name: Check Pull Request

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v5

      - name: Run luacheck
        uses: dekallo/luacheck@main
        with:
          args: -q
          run_luacheck: false
          test_script: scripts/validate.lua
          test_args: "--fail"
